# Direct and Indirect Speech

He has just said that the ship ... at the end of
the week.

?? will arrive
?? would arrive
?? arrives
?? is arriving

He says that she ... in the evening.

?? will come
?? shall come
?? would come
?? come

He ... just ... me that the negotiations have begun.

?? has told
?? have told
?? had told
?? told

He said that he ... an interesting book.

?? was reading
?? is reading
?? reads
?? read

He said that he ... to the manager about the terms
of delivery of the machine.

?? had spoken
?? has spoken
?? have spoken
?? spoke

He said that he ... for me since five o'clock.

?? had been working
?? worked
?? had worked
?? was working

He said that the contract ... in the evening.

?? would be signed
?? will be sign
?? was signed
?? will sign

He said that they ... the steamer by six o'clock.

?? would have unloaded
?? would unloaded
?? have unloaded
?? unloaded

He said that they ... their work by six o'clock.

?? had finished
?? finished
?? would finished
?? may finished

She said that she met him when she ... the road.

?? was crossing
?? crossed
?? were crossing
?? is crossing

She said that she ... there the day before.

?? had been
?? has been
?? was
?? were

He told her that she ... consult a doctor.

?? must
?? will
?? would
?? should

He said that he would write the letter ... .

?? the next day
?? two days later
?? before
?? the day before

He said that he had been there the ... .

?? day before
?? following year
?? next year
?? next day

I asked him why he ... so late.

?? had come
?? has come
?? came
?? comes

He asked me where I ... the day before.

?? had been
?? was
?? were
?? has been

He asked me ... I had received their answer.

?? whether
?? ---
?? when
?? how

He asked me if I ... there the next day.

?? should be
?? would be
?? shall be
?? will be

She told him ... at five o'clock.

?? to come
?? will come
?? shall come
?? come

He asked me what the price of this car ... .

?? was
?? ---
?? were
?? is
