# Combined test

# Вариант централизованного тестирования.

I ... . That's why my hair is wet

?? have bathed
?? had been bathing
?? bathed
?? was bathing

I ... how thought your room would be more spacious.

?? some
?? any
?? no
?? every

It was only two hours after the fire broke out that
the fireman ... extinguish the fire.

?? were able to
?? could
?? must
?? had to

He ... in silence for five minutes then he put out
his cigarette and left the room.

?? had been smoking
?? had smoked
?? was smoking
?? smoked

How I wish I ... him the whole truth! Now that he
knows everything he is suffering so much!

?? hadn't told
?? didn't tell
?? haven't told
?? wouldn't tell

The lecture is really worth ... .

?? attending
?? to be attended
?? being attended
?? to attend

There are just three of them in this flat, Betsy is
... only child.

?? the
?? a
?? an
?? ---

He speaks as if he ... him well though he has never
seen him!

?? knew
?? is known
?? knows
?? had known

... he still be talking on the phone? I've asked him
several times to help mother.

?? Can
?? Can't
?? May
?? Must

They agreed that Martin would provide her with all
the equipment on condition he ... his salary in time.

?? would get
?? gets
?? will get
?? got

The castle was built in the 12th century and the church
beside it is equally ... .

?? ancient
?? antique
?? elderly
?? old-fashioned

My sister's son. Jimmy is my favourite ... .

?? nephew
?? cousin
?? niece
?? uncle

It was supposed to rain yesterday, according to
weather ... .

?? forecast
?? prognosis
?? prediction
?? warning

Because of the bad weather we had to ... our picnic.

?? put off
?? put aside
?? put out
?? put up

What are you looking ... ? --- My glasses. I can't find
them anywhere.

?? for
?? at
?? after
?? through
