# Passive Voice

# Comments...
# Первый ответ - правильный

He is expected ... the article by Friday.

?? to have written
?? wrote
?? to be writing
?? writing

The room ... when I arrived.

?? was being cleaned
?? cleaned
?? was cleaning
?? is being cleaned

His face ... with anger.

?? was distorted
?? being distorting
?? distorted
?? distort

He ... to edit the local newspaper.

?? has been asked
?? were asked
?? was asking
?? asked

"Dracula" is a name that ... by many people today.

?? is known
?? knows
?? has been known
?? has known

Someone is making pizza. The pizza is ... by someone.

?? being made
?? made
?? going to be made
?? making

Our work ... as soon as possible.

?? must be finished
?? must finished
?? must finishing
?? must being finished

This book ... in any bookshop.

?? can be bought
?? can bought
?? can be buying
?? can buy

This article ought ... at once.

?? to be translated
?? be translated
?? being translate
?? translating

The goods are ... by the end of the month.

?? to be delivered
?? to be delivering
?? to deliver
?? delivering

Business letters ... on specials forms.

?? are usually written
?? usually written
?? usually are written
?? writing

The matter ... at the next meeting.

?? will be discussed
?? to have been discussed
?? had been discussed
?? to be discussed

The bridge ... next year.

?? will be built
?? will build
?? will built
?? will be build

This question ... when I entered the room.

?? was being discussed
?? has discussed
?? was discussing
?? is being discussed

The letter ... just ... .

?? has been typed
?? was typed
?? had been typed
?? had typed

The article will ... by six o'clock.

?? have been translated
?? had been translated
?? having been translated
?? being translated

I'll be very glad if your article ... in the newspaper.

?? is published
?? will published
?? will be published
?? would published

He said very important questions ... at the conference.

?? were being discussed
?? are discussed
?? are being discussed
?? were discussed

He said that he would show us the letter when it ... .

?? was typed
?? will be typed
?? are typed
?? would be typed

I knew that very tasty pizza ... by someone.

?? was delivered
?? was being delivered
?? is delivered
?? is delivering
