# The Subjunctive Mood

# Comments...
# Первый ответ - правильный

If I had seen when you pass me in the street, I ... hello.

?? would have said
?? will say
?? would say
?? had said

She wanted to know whether ... driving licence.

?? did I have
?? I having
?? I had
?? do I have

If I ... you, I wouldn't buy that coat.

?? were
?? was
?? am
?? will be

If I had chance to meet a celebrity, I ... our President.

?? would loved meet
?? shall meet
?? will have meet
?? wish

If I ... money, I would have bought a car.

?? had had
?? had
?? had have
?? have

If you ... an advertisement you may soon find a buyer for it.

?? insert
?? will insert
?? inserted
?? would insert

How I wish I ... him the whole truth! Now that he knows
everything he is suffering so much!

?? hadn't told
?? haven't told
?? didn't tell
?? wouldn't tell

If he ... the regulation, he will be fined.

?? break
?? will break
?? would break
?? broke

They ... if they had had any further news.

?? would have called
?? have called
?? will call
?? would had called

If I ... him tomorrow, I'd ask him about it.

?? saw
?? see
?? will see
?? would have seen

I wish he ... with us.

?? were
?? was
?? has been
?? was being

I wish I ... more time for learning.

?? had
?? had had
?? have
?? will have

If I ... him yesterday, I should have asked him about it.

?? had seen
?? have seen
?? saw
?? have seeing

If I ... that book anywhere.

?? had found
?? found
?? find
?? shall find

If he had met us, he ... to the country with us.

?? would have gone
?? would gone
?? will have gone
?? have gone

He wished they ... him like a lot of sheep.

?? wouldn't follow
?? would follow
?? had followed
?? hadn't followed

I wish he ... with us.

?? were
?? was
?? have been
?? would be

He spoke as if he ... a specialist on the subject.

?? were
?? would be
?? is
?? was

They covered the goods with canvas lest they ... by rain.

?? be damaged
?? weren't damaged
?? were damaged
?? damaged

He suggested that the question ... at the next meeting.

?? be discussed
?? will discuss
?? would discuss
?? discuss
