# Sequence of Tenses

# Comments...
# Первый ответ - правильный

The telephone rang but I didn't hear it. I ... asleep.

?? must have been
?? had to be
?? having been
?? must be

When I came into the shop. I realized that
I ... money at home.

?? had left
?? left
?? leave
?? was leaving

The church ... when I arrived.

?? was being built
?? built
?? was building
?? is being built

By the time we reached our destination, it ... dark.

?? had already become
?? had been becoming
?? has already become
?? was becoming

The explorer disappeared while he ... the Atlantic ocean.

?? was crossing
?? had crossed
?? crossed
?? had been crossing

When the court was in session, the judge ... entrance
by anyone.

?? wouldn't  permit
?? won't permit
?? didn't permit
?? wouldn't has permit

I had to be up early next morning, so I ... myself
and left the party.

?? excused
?? refused
?? thanked
?? apologized

He suggests, that prominent people ... to contribute.

?? should be asked
?? would being asked
?? would have been asking
?? will ask

Why are you walking so fast? I'm hurrying because
I ... my mother at four o'clock and she doesn't ... .

?? to be kept waiting
?? to be keeping wait
?? to be being kept waiting
?? to keep waiting for

We didn't know the score, but we were sure their
team ... the game.

?? had lost
?? has lost
?? lost
?? had been lost

The children were afraid of making any noise. - Mom ... .

?? was sleeping
?? slept
?? had been sleeping
?? was being slept

She confirmed that she ... to get married soon.

?? was going
?? has gone
?? went
?? is going

Your car stopped before I realized we ... there already.

?? were
?? have been
?? are
?? should have been

I ... leave if you're going to speak to me like this.

?? would rather
?? would better
?? had rather
?? had better

I just want to know if this program ... broadcast at
7.30 tonight as it's been settled.

?? will be
?? is being
?? is
?? will be being

My brother ... the tape recorder, and now it wouldn't work.

?? has used
?? has been using
?? had used
?? was using

She said she didn't like her present flat
and ... to find a new one.

?? was trying
?? had been trying
?? tried
?? is trying

He ... in silence for five minutes, then he put out
cigarette and left the room.

?? had being smoking
?? was smoking
?? had smoked
?? smoked

He speaks as if he ... him well though he has never seen him.

?? knew
?? is known
?? knows
?? had known

They agreed that Martin would provide her with all the
equipment on condition he ... his salary in time.

?? would get
?? gets
?? will get
?? got
